### ISSUE TITLE
Памылка ў родзе пераклада

### ISSUE THREAD

**Issue by SergDred** [gitReiko/by-lang-mb-bannerlord#16]
Не ведаю як тут дакладна працуе пераклад, але здаецца, што дадзены радок дыялога выкарыстоўваецца ад асобы персанажа жаночага роду.

https://github.com/gitReiko/by-lang-mb-bannerlord/blob/3b1e0f209aadcb0e8dc94e5adde20208621609b2/%D0%BF%D0%B5%D1%80%D0%B0%D0%BA%D0%BB%D0%B0%D0%B4%D1%8B%20%D0%B3%D1%83%D0%BB%D1%8C%D0%BD%D1%96/e1.8.1/Belarusian.Core/ModuleData/Languages/BYc/SandBox/std_wanderer_strings_xml_by.xml#L266
![Screenshot 2022-12-28 014116](https://user-images.githubusercontent.com/948597/209734274-298a2496-97f0-4c2a-ba47-90c77f965d7d.png)

**Comment by SergDred** [comment]
Вось яшчэ адзін момант які знайшоў.
![Screenshot 2022-12-28 021638](https://user-images.githubusercontent.com/948597/209735800-ab8c5001-b358-467c-bb6a-9cacc2ff1a48.png)

**Comment by gitReiko** [comment]
[SergDred](https://github.com/SergDred) Вітаю, дзякуй за дапамогу. Выправіў памылкі ў праекце перакладу. Калі назапасіцца досыць зменаў, абнаўлю пераклад на нэксусе і стыме.

1. У першых выпадку, амаль немагчыма зразумець род персанажа, ад якого вядзецца дыялог. 
2. У другім была мая памылка ў пераменнай рода.
